/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NewBuild;

public class App {
    public static void main(String[] args) {
        HttpServer.getInstance().start();
    }
}
